In [ ]:
!pip install -U -q PyDrive
from pydrive.auth import GoogleAuth
from pydrive.drive import GoogleDrive
from google.colab import auth
from oauth2client.client import GoogleCredentials
# 1. Authenticate and create the PyDrive client.
auth.authenticate_user()
gauth = GoogleAuth()
gauth.credentials = GoogleCredentials.get_application_default()
drive = GoogleDrive(gauth)

In [ ]:
# 2. Mount Drive
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [2]:
import numpy as np
import cv2
from google.colab.patches import cv2_imshow

### IN THE BELOW CODE THE POINTS WE GIVE ARE MAPPED TO CORNERS

In [ ]:
img = cv2.imread("drive/My Drive/Images_for_Adarsh/DSC_0690.JPG")

height,width = 1000,1500
img = cv2.resize(img,(width,height))

pts1 = np.float32([[ 250, 0],[1220, 300],[1300, 770],[ 250, 860]])
pts2 = np.float32([[0,0],[width,0],[width,height],[0,height]])
matrix = cv2.getPerspectiveTransform(pts1,pts2)


print(matrix.shape)
print(matrix)
imgOutput = cv2.warpPerspective(img,matrix,(width,height))
cv2_imshow(imgOutput)
cv2.imwrite("drive/My Drive/PerspectiveWarp-Results1/0690_coarse/0690([[ 250, 0],[1220, 300],[1300, 770],[ 250, 860]]).JPG",imgOutput)




Output hidden; open in https://colab.research.google.com to view.

### IN THE BELOW CODE THE POINTS ARE MAPPED SO THAT FIRST POINT IS AT SAME PIXEL LOCATION AND REST ARE ADJUSTED TO FORM A RECTANGLE, TAKING INTO ACCOUNT THE DISTANCE BETWEEN THE POINTS

In [ ]:
img = cv2.imread("drive/My Drive/Images_for_Adarsh/DSC_6181.JPG")

height1,width1 = 1000,1500
img = cv2.resize(img,(1500,1000))

#circles = [[520, 443], [718, 453], [722, 794], [511, 800]]
circles =[[1021, 473], [1090, 478], [1120, 778], [1049, 782]]


circles  = np.array(circles)

pts1 = np.float32([circles[0],circles[1],circles[2],circles[3]])

width = np.sqrt((circles[1][0] - circles[0][0])**2 + (circles[1][1] - circles[0][1])**2)
height =  np.sqrt((circles[2][1] - circles[0][1])**2 + (circles[2][0] - circles[0][0])**2)
width = int(np.round(width))
height = int(np.round(height))
x1,y1 = circles[0]

pts2 = np.float32([[x1,y1],[(x1+width),y1],[(x1+width),(y1+height)],[x1,(y1+height)]])
matrix = cv2.getPerspectiveTransform(pts1,pts2)

print(matrix.shape)
print(matrix)

img = cv2.cvtColor(img, cv2.COLOR_BGR2BGRA)
imgOutput = cv2.warpPerspective(img,matrix,(width1,height1),cv2.INTER_LINEAR, borderMode=cv2.BORDER_CONSTANT, borderValue=(0,0,0,0))
cv2_imshow(imgOutput)
#cv2.imwrite("drive/My Drive/PerspectiveWarp-Results1/0273([[462, 258], [568, 167], [565, 356], [450, 424]]).JPG",imgOutput)
#cv2.imwrite("drive/My Drive/dummy/dummyPersp_Warp.JPG",imgOutput)



Output hidden; open in https://colab.research.google.com to view.

### THE CODE I GOT FROM STACK OVERFLOW

In [ ]:
img = Image.open("drive/My Drive/dummy/dummyPersp_Warp.JPG")

for i in range(img.shape[0]):
    for j in range(img.shape[1]):

        if img[i][j][0]==0 and img[i][j][1]==0 and img[i][j][2]==0:
            img.putalpha(0)
        else:
            img.putalpha(255)
display(img)

In [ ]:



img = cv2.imread("building.jpg")

# resize
height,width = 1000,1500
img = cv2.resize(img, (width,height))

# specify conjugate coordinates and shift output on left and top
pts1 = np.float32([[ 250, 0],[1220, 300],[1300, 770],[ 250, 860]])
pts2 = np.float32([[+500,+500],[width+500,+500],[width+500,height+500],[+500,height+500]])

# compute perspective matrix
matrix = cv2.getPerspectiveTransform(pts1,pts2)

print(matrix.shape)
print(matrix)

# convert image to BGRA with opaque alpha
img = cv2.cvtColor(img, cv2.COLOR_BGR2BGRA)

# do perspective transformation setting area outside input to transparent
# extend output size so extended by 500 all around
imgOutput = cv2.warpPerspective(img, matrix, (width+1000,height+1000), cv2.INTER_LINEAR, borderMode=cv2.BORDER_CONSTANT, borderValue=(0,0,0,0))

# resize output, since it is too large to post
imgOutput = cv2.resize(imgOutput, (width,height))
    
# save the warped output
cv2.imwrite("building_warped.png", imgOutput)

# show the result
cv2.imshow("result", imgOutput)

## THE POINTS FOR EACH IMAGE

In [ ]:
# circles6181 = [[1021, 473], [1090, 478], [1120, 778], [1049, 782]]
# circles6176 = [[476, 463], [545,453], [538,714], [467,717]]
# circles0690 = [[1043, 424], [1076, 429], [1092, 611], [1059, 610]]
# circles0690q = [[1017, 365], [1055, 371], [1084, 691], [1046, 692]]
# circles0690qq =[[1087, 380],[1121,  387] ,[1152,  690], [1118,  690]]
# circles6120 = [[201, 523], [298, 519], [285, 695], [187, 694]]
# circles6139 =[[402, 351], [464, 349], [449, 531], [386, 532]]
# circles6138 =[[414, 366], [503, 362], [479, 586], [388, 586]]
# circles0244 =[[171, 484], [219, 467], [152, 719], [ 97, 738]]
# circles0273 =[[462, 258], [568, 167], [565, 356], [450, 424]]

### IN THE BELOW CODE THE POINTS ARE MAPPED SO THAT FIRST POINT IS AT SAME PIXEL LOCATION AND REST ARE ADJUSTED TO FORM A RECTANGLE, TAKING INTO ACCOUNT THE DISTANCE BETWEEN THE POINTS.
## THE ONLY DIFFERENCE IS HERE, HOMOGRAPHY MATRIX IS USED

In [ ]:
img = cv2.imread("drive/My Drive/Images_for_Adarsh/DSC_6181.JPG")

height1,width1 = 1000,1500
img = cv2.resize(img,(1500,1000))

#circles = [[520, 443], [718, 453], [722, 794], [511, 800]]
circles =[[1021, 473], [1090, 478], [1120, 778], [1049, 782]]

circles  = np.array(circles)

pts1 = np.float32([circles[0],circles[1],circles[2],circles[3]])

width = np.sqrt((circles[1][0] - circles[0][0])**2 + (circles[1][1] - circles[0][1])**2)
height =  np.sqrt((circles[2][1] - circles[0][1])**2 + (circles[2][0] - circles[0][0])**2)
width = int(np.round(width))
height = int(np.round(height))
x1,y1 = circles[0]

pts2 = np.float32([[x1,y1],[(x1+width),y1],[(x1+width),(y1+height)],[x1,(y1+height)]])
matrix, q123 = cv2.findHomography(pts1,pts2)
imgf = cv2.warpPerspective(img, matrix, (1500,1000))
print(matrix)
cv2_imshow(imgf)


[[ 4.00041029e-01  6.71168336e-02  3.14262589e+02]
 [-2.07764586e-01  8.66841066e-01  1.51627196e+02]
 [-3.15858523e-04  1.29861941e-04  1.00000000e+00]]
